<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>registrosocial-service</artifactId>
  <build>
    <plugins>
      <!-- Plugin para configurar la compilación y especificar procesadores de anotación -->
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <artifactId>therapi-runtime-javadoc-scribe</artifactId>
              <groupId>com.github.therapi</groupId>
              <version>0.15.0</version>
            </path>
            <path>
              <artifactId>lombok</artifactId>
              <groupId>org.projectlombok</groupId>
              <version>${lombok.version}</version>
            </path>
            <path>
              <artifactId>mapstruct-processor</artifactId>
              <groupId>org.mapstruct</groupId>
              <version>${mapstruct.version}</version>
            </path>
            <path>
              <artifactId>lombok-mapstruct-binding</artifactId>
              <groupId>org.projectlombok</groupId>
              <version>${lombok-mapstruct-binding.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
        <groupId>org.apache.maven.plugins</groupId>
        <version>${maven-compiler-plugin.version}</version>
      </plugin>
      <!-- Plugin para generar referencias cruzadas de código fuente para documentación -->
      <plugin>
        <artifactId>maven-jxr-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>jxr</goal>
              <goal>test-jxr</goal>
            </goals>
            <id>cross-reference-source</id>
            <phase>pre-site</phase>
          </execution>
        </executions>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.3.1</version>
      </plugin>
      <!-- Plugin para ejecutar tests unitarios -->
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.2.2</version>
      </plugin>
      <!-- Plugin para ejecutar pruebas de integración y verificación -->
      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.2.2</version>
      </plugin>
      <!-- Plugin para detectar bugs potenciales en el código usando SpotBugs -->
      <!--<plugin>
        <artifactId>spotbugs-maven-plugin</artifactId>
        <configuration>
          <failOnError>false</failOnError>
          <includeTests>true</includeTests>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
            <id>verificar-bugs</id>
            <phase>verify</phase>
          </execution>
        </executions>
        <groupId>com.github.spotbugs</groupId>
        <version>4.8.1.0</version>
      </plugin>-->
      <!-- Plugin para generar documentación JavaDoc -->
      <plugin>
        <artifactId>maven-javadoc-plugin</artifactId>
        <configuration>
          <nohelp>true</nohelp>
          <show>private</show>
        </configuration>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.6.2</version>
      </plugin>
      <!-- Plugin para manejar releases y versionado -->
      <plugin>
        <artifactId>maven-release-plugin</artifactId>
        <configuration>
          <tagNameFormat>v@{project.version}</tagNameFormat>
        </configuration>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.0.1</version>
      </plugin>
      <!-- Plugin para ejecutar análisis de código estático usando PMD -->
      <plugin>
        <artifactId>maven-pmd-plugin</artifactId>
        <configuration>
          <excludes>
          </excludes>
          <failOnViolation>true</failOnViolation>
          <includeTests>true</includeTests>
          <rulesets>
      <!--<ruleset>http://10.1.22.164/analisis-codigo/analisis-codigo/-/raw/main/pmd-ruleset.xml
     </ruleset>-->
   </rulesets>
   <skipEmptyReport>false</skipEmptyReport>
   <verbose>true</verbose>
 </configuration>
 <executions>
   <execution>
     <configuration>
       <excludeFromFailureFile>
         ${project.parent.relativePath}/semop-monitoring-container/src/test/resources/aud-codigo/exclude-pmd.properties
       </excludeFromFailureFile>
     </configuration>
     <goals>
       <goal>check</goal>
     </goals>
     <id>check-pmd</id>
     <phase>verify</phase>
   </execution>
   <execution>
     <configuration>
       <excludeFromFailureFile>
         ${project.parent.relativePath}/semop-monitoring-container/src/test/resources/aud-codigo/exclude-pmd.properties
       </excludeFromFailureFile>
     </configuration>
     <goals>
       <goal>check</goal>
     </goals>
     <id>report-pmd</id>
     <phase>site</phase>
   </execution>
 </executions>
 <groupId>org.apache.maven.plugins</groupId>
 <version>${maven-pmd-plugin.version}</version>
</plugin>
<!-- Plugin para chequear dependencias por vulnerabilidades conocidas -->
      <!--plugin>
        <artifactId>dependency-check-maven</artifactId>
        <configuration>
          <autoUpdate>true</autoUpdate>
          <nvdApiDelay>32000</nvdApiDelay>
          <nvdApiKey>dcb24e47-1766-47a2-b6ef-248f3ed7949c</nvdApiKey>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
        <groupId>org.owasp</groupId>
        <version>${dependency-check-maven.version}</version>
      </plugin-->
      <!-- Plugin para aplicar reglas de estilo y formato (Checkstyle) -->
      <plugin>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <configuration>
          <configLocation>
            http://10.1.22.164/analisis-codigo/analisis-codigo/-/raw/main/checkstyle.xml
          </configLocation>
          <consoleOutput>true</consoleOutput>
          <failsOnError>true</failsOnError>
        </configuration>
        <groupId>org.apache.maven.plugins</groupId>
        <version>${maven-checkstyle-plugin.version}</version>
      </plugin>
      <!-- Plugin para integración con SonarQube y análisis de calidad de código -->
      <plugin>
        <artifactId>sonar-maven-plugin</artifactId>
        <groupId>org.sonarsource.scanner.maven</groupId>
        <version>${sonar-maven-plugin.version}</version>
      </plugin>
    </plugins>
  </build>
  <dependencies>
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
    </dependency>
    <dependency>
      <artifactId>spring-boot-problem-handler</artifactId>
      <groupId>io.github.officiallysingh</groupId>
      <version>${spring-boot-problem-handler.version}</version>
    </dependency>
    <dependency>
      <artifactId>therapi-runtime-javadoc</artifactId>
      <groupId>com.github.therapi</groupId>
      <version>0.15.0</version>
    </dependency>
    <dependency>
      <artifactId>lombok</artifactId>
      <groupId>org.projectlombok</groupId>
      <scope>provided</scope>
      <version>${lombok.version}</version>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-logging</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>mapstruct</artifactId>
      <groupId>org.mapstruct</groupId>
      <version>1.5.5.Final</version>
    </dependency>
    <dependency>
      <artifactId>jakarta.validation-api</artifactId>
      <groupId>jakarta.validation</groupId>
    </dependency>
    <dependency>
      <artifactId>hibernate-validator</artifactId>
      <groupId>org.hibernate.validator</groupId>
    </dependency>
    <dependency>
      <artifactId>jackson-annotations</artifactId>
      <groupId>com.fasterxml.jackson.core</groupId>
    </dependency>
    <dependency>
      <artifactId>redisson</artifactId>
      <groupId>org.redisson</groupId>
      <version>${redisson.version}</version>
    </dependency>
  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <artifactId>registrosocial-application-service</artifactId>
        <groupId>${project.groupId}</groupId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <artifactId>registrosocial-container-service</artifactId>
        <groupId>${project.groupId}</groupId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <artifactId>registrosocial-dataaccess-service</artifactId>
        <groupId>${project.groupId}</groupId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <artifactId>registrosocial-domain-application-service</artifactId>
        <groupId>${project.groupId}</groupId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <artifactId>registrosocial-domain-core-service</artifactId>
        <groupId>${project.groupId}</groupId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <artifactId>registrosocial-common-service</artifactId>
        <groupId>${project.groupId}</groupId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <artifactId>spring-cloud-dependencies</artifactId>
        <groupId>org.springframework.cloud</groupId>
        <scope>import</scope>
        <type>pom</type>
        <version>${spring-cloud.version}</version>
      </dependency>
      <dependency>
        <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        <groupId>org.springdoc</groupId>
        <version>2.2.0</version>
      </dependency>
      <dependency>
        <artifactId>HikariCP</artifactId>
        <groupId>com.zaxxer</groupId>
        <version>${hikari.cp.version}</version>
      </dependency>
      <dependency>
        <artifactId>datasource-proxy-spring-boot-starter</artifactId>
        <groupId>com.github.gavlyukovskiy</groupId>
        <version>${datasource.proxy.version}</version>
      </dependency>
      <dependency>
        <artifactId>caffeine</artifactId>
        <groupId>com.github.ben-manes.caffeine</groupId>
        <version>3.1.8</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <description>Proyecto base, arquetipo base para el resto de proyectos</description>
  <developers>
    <developer>
      <email>e.du.ingcharles@hotmail.comc</email>
      <name>Carlos Eduardo Anchundia Valencia</name>
      <organization>
        Subdirección Nacional de Sistemas de Información -
        Desarrollo de Software -
        Arquitectura de Software
      </organization>
      <organizationUrl>https://www.registrosocial.gob.ec/</organizationUrl>
    </developer>
  </developers>
  <groupId>ec.gob.registrosocial</groupId>
  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0</url>
    </license>
  </licenses>
  <modelVersion>4.0.0</modelVersion>
  <modules>
    <module>registrosocial-application-service</module>
    <module>registrosocial-container-service</module>
    <module>registrosocial-dataaccess-service</module>
    <module>registrosocial-domain-service</module>
    <module>registrosocial-common-service</module>
  </modules>
  <packaging>pom</packaging>
  <parent>
    <artifactId>spring-boot-starter-parent</artifactId>
    <groupId>org.springframework.boot</groupId>
    <version>3.2.5</version>
  </parent>
  <pluginRepositories>
    <pluginRepository>
      <id>central</id>
      <name>Maven Repository Switchboard</name>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <url>https://repo.maven.apache.org/maven2</url>
    </pluginRepository>
    <pluginRepository>
      <id>spring-milestones</id>
      <name>Spring Milestones</name>
      <url>https://repo.spring.io/milestone</url>
    </pluginRepository>
  </pluginRepositories>
  <properties>
    <datasource.proxy.version>1.9.0</datasource.proxy.version>
    <dependency-check-maven.version>9.0.1</dependency-check-maven.version>
    <hikari.cp.version>5.0.1</hikari.cp.version>
    <jacoco-maven-plugin.version>0.8.11</jacoco-maven-plugin.version>
    <java.version>23</java.version>
    <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
    <lombok.version>1.18.30</lombok.version>
    <mapstruct.version>1.5.5.Final</mapstruct.version>
    <maven-checkstyle-plugin.version>3.3.1</maven-checkstyle-plugin.version>
    <maven-compiler-plugin.version>3.11.0</maven-compiler-plugin.version>
    <maven-pmd-plugin.version>3.21.2</maven-pmd-plugin.version>
    <mockito.version>4.5.1</mockito.version>
    <postgresql.version>42.7.3</postgresql.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <redisson.version>3.25.2</redisson.version>
    <sonar-maven-plugin.version>3.10.0.2594</sonar-maven-plugin.version>
    <spring-boot-problem-handler.version>1.7</spring-boot-problem-handler.version>
    <spring-boot.version>3.1.3</spring-boot.version>
    <spring-cloud.version>2023.0.0</spring-cloud.version>
    <springdoc.version>1.7.0</springdoc.version>
  </properties>
  <repositories>
    <repository>
      <id>central</id>
      <name>Maven Repository Switchboard</name>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <url>https://repo.maven.apache.org/maven2</url>
    </repository>
    <repository>
      <id>repository.spring.release</id>
      <name>Spring GA Repository</name>
      <url>http://repo.spring.io/release</url>
    </repository>
    <repository>
      <id>spring-milestones</id>
      <name>Spring Milestones</name>
      <url>https://repo.spring.io/milestone</url>
    </repository>
    <repository>
      <id>spring-central</id>
      <name>libs-release</name>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <url>https://repo.spring.io/libs-release</url>
    </repository>
    <repository>
      <id>snapshots</id>
      <name>libs-snapshot</name>
      <snapshots/>
      <url>https://repo.spring.io/libs-snapshot</url>
    </repository>
    <repository>
      <id>spotify-public</id>
      <url>https://repo.spotify.com/maven2/</url>
    </repository>
  </repositories>
  <scm>
    <url>http://10.1.22.164/infraestructura/base/eva-proyecto-base.git</url>
  </scm>
  <url>http://10.1.22.164/infraestructura/base/eva-proceso-service.git</url>
  <version>1.0.0-SNAPSHOT</version>
</project>
