<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>registrosocial-container-service</artifactId>
  <dependencies>
    <dependency>
      <artifactId>registrosocial-application-service</artifactId>
      <groupId>${project.groupId}</groupId>
    </dependency>
    <dependency>
      <artifactId>registrosocial-domain-application-service</artifactId>
      <groupId>${project.groupId}</groupId>
    </dependency>
    <dependency>
      <artifactId>registrosocial-domain-core-service</artifactId>
      <groupId>${project.groupId}</groupId>
    </dependency>
    <dependency>
      <artifactId>registrosocial-dataaccess-service</artifactId>
      <groupId>${project.groupId}</groupId>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>

    <dependency>
      <artifactId>spring-cloud-starter-config</artifactId>
      <groupId>org.springframework.cloud</groupId>
    </dependency>

    <dependency>
      <artifactId>spring-boot-starter-cache</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>caffeine</artifactId>
      <groupId>com.github.ben-manes.caffeine</groupId>
    </dependency>
    <!--Prometheus, Zipkin & Micrometer-->
<!--    <dependency>-->
<!--      <artifactId>micrometer-registry-prometheus</artifactId>-->
<!--      <groupId>io.micrometer</groupId>-->
<!--      <scope>runtime</scope>-->
<!--    </dependency>-->
    <dependency>
      <artifactId>micrometer-tracing-bridge-brave</artifactId>
      <groupId>io.micrometer</groupId>
    </dependency>
    <!--Actuator & AOP-->
    <dependency>
      <artifactId>spring-boot-starter-actuator</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-aop</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <artifactId>spring-cloud-dependencies</artifactId>
        <groupId>org.springframework.cloud</groupId>
        <scope>import</scope>
        <type>pom</type>
        <version>${spring-cloud.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <modelVersion>4.0.0</modelVersion>
<!--  <profiles>-->
<!--    <profile>-->
<!--      <build>-->
<!--        <plugins>-->
<!--          <plugin>-->
<!--            <artifactId>spring-boot-maven-plugin</artifactId>-->
<!--            <configuration>-->
<!--              <image>-->
<!--                <createdDate>now</createdDate>-->
<!--                <env>-->
<!--                  <BPE_APPEND_JAVA_TOOL_OPTIONS>-->
<!--                    -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=1024M-->
<!--                    -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true-->
<!--                    -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -Xss512k-->
<!--                    -Dfile.encoding=UTF-8 -Duser.timezone=GMT-5 -Duser.language=es -Duser.region=EC-->
<!--                    -XX:ParallelGCThreads=4 -XX:InitiatingHeapOccupancyPercent=70-->
<!--                    -XX:+UseStringDeduplication -XX:ConcGCThreads=4 -XX:+ParallelRefProcEnabled-->
<!--                    -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20-->
<!--                    -XX:G1MaxNewSizePercent=60-->
<!--                    -XX:G1HeapRegionSize=32M -XX:G1HeapWastePercent=5-->
<!--                    -XX:G1MixedGCLiveThresholdPercent=85 -XX:G1MixedGCCountTarget=4-->
<!--                    -XX:G1OldCSetRegionThresholdPercent=10-->
<!--                  </BPE_APPEND_JAVA_TOOL_OPTIONS>-->
<!--                  <BPE_DELIM_JAVA_TOOL_OPTIONS xml:space="preserve"> </BPE_DELIM_JAVA_TOOL_OPTIONS>-->
<!--                  <BP_JVM_VERSION>${java.version}</BP_JVM_VERSION>-->
<!--                </env>-->
<!--                <name>${project.groupId}/${project.parent.artifactId}:${project.version}</name>-->
<!--              </image>-->
<!--            </configuration>-->
<!--            <executions>-->
<!--              <execution>-->
<!--                <goals>-->
<!--                  <goal>build-image</goal>-->
<!--                </goals>-->
<!--                <phase>package</phase>-->
<!--              </execution>-->
<!--            </executions>-->
<!--            <groupId>org.springframework.boot</groupId>-->
<!--          </plugin>-->
<!--        </plugins>-->
<!--      </build>-->
<!--      <id>generar-imagen-docker</id>-->
<!--    </profile>-->
<!--  </profiles>-->
  <parent>
    <groupId>ec.gob.registrosocial</groupId>
    <artifactId>registrosocial-service</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>
</project>
